# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 511090b052420b1db91851011794d8dad613f6e23f929a267e5f3bb7c29d7bda7bf0501b58c6fe24469b0eac3e0cf7a2c6e57b687a47203658533d6d0b1b2927

test:
  secret_key_base: 6bfca3f8ca684cc8a62b46e52f985ec3d15f939ae57a732aeee66584c5ddd8ec5daa0ec62c7130a388891e41ff4a29a861e4d8662ac82dac02e8c012fff246eb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
